language: node_js
node_js:
  - "iojs"

branches:
  only:
    - master
addons:
  apt:
    packages:
      - sshpass

install:
  - npm install -g bower gulp
  - npm install
  - bower install

after_success:
  - tar -cvzf package.tgz dist
  - export SSHPASS=$DEPLOY_PASS
  - sshpass -e scp -v -o stricthostkeychecking=no -P $DEPLOY_PORT package.tgz $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH
  - sshpass -e ssh -v -p $DEPLOY_PORT $DEPLOY_USER@$DEPLOY_HOST $DEPLOY_PATH/deploy.sh $TRAVIS_BRANCH
